session_name: qq_red_packet
windows:
  - window_name: qq_red_packet_window
    layout: tiled
    shell_command_before:
      - cd ~/Desktop/works/pyjom # run as a first command in all panes
      - bash # to ensure we use the right shell
      - conda deactivate # to disable conda enviorment
    panes:
      - shell_command:
          - cd tests/qq_opqbot
          - cd opq_arm64
          - bash launch.sh # will kill all opqbots.
      - shell_command: # magic from https://www.wikitechy.com/tutorials/linux/how-to-write-stderr-to-a-file-while-using-tee-with-a-pipe
          - sleep 10
          - cd tasks/qq/qq_red_packet_collect # run multiple commands in this pane
          - keepalive python3 botoy_redpacket_collect.py 1>/dev/null 2> >(tee -a logs/redPacketLog_0.log >&2)
          # - python3 botoy_redpacket_collect.py 1>/dev/null
        #   - python3 botoy_redpacket_collect.py --log 1 --log_file 0 1>/dev/null 2> >(tee -a redPacketLog_0.log >&2)
      # it seems we need another github account to have another gitter developer token.
      - shell_command:
          - cd tests/qq_opqbot
          - cd opq_arm64_another_account
          - sleep 3
          - bash launch.sh # port 8784
      - shell_command:
          - sleep 10
          - cd tasks/qq/qq_red_packet_collect # run multiple commands in this pane
          - keepalive python3 botoy_redpacket_collect.py --qq 917521610 --port 8784 1>/dev/null 2> >(tee -a logs/redPacketLog_1.log >&2)
          # - python3 botoy_redpacket_collect.py --qq 917521610 --port 8784 1>/dev/null 
        #   - python3 botoy_redpacket_collect.py  --log 1 --log_file 0 --qq 917521610 --port 8784 1>/dev/null 2> >(tee -a redPacketLog_1.log >&2)
      - shell_command: # GPT2 LOCAL CHATBOT SERVER
          - cd tests/cpm_chinese_chitchat_model_gpt2/server/
          - bash launch.sh
      - shell_command: # text censor api
          - cd tasks/qq/qq_red_packet_collect/textfilter 
          - bash launch.sh
      - shell_command: # image dog/cat recognition server
          - cd tests/bezier_paddlehub_dogcat_detector_serving
          - python3 server.py
      - shell_command:
          - cd tests/bilibili_video_recommendation_server
          - python3 test.py
      - shell_command: # xiaoice chat api
          - cd tests/microsoft_xiaobing_conversation_bing
          # - node chat_with_session_id.js
          # - bash xiaobing_server_keepalive.sh
          - keepalive node chat_with_session_id.js # try it. you may want to replace it with python.
      # login first!
      # when pasting gitter tokens, be careful.