platform:
  - x64

environment:
  matrix:
  # - nodejs_version: "12"
  # - nodejs_version: "14"
  - nodejs_version: "16"

install:
  - cmd: git submodule update --init
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
  - npm config set msvs_version 2015 --global
  - npm config set target_arch %PLATFORM% --global
  - npm install -g node-gyp

build_script:
  - npm install --ignore-scripts
  - npm run rebuild

test_script:
  - npm test

deploy_script:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") {./node_modules/.bin/prebuild -t 12.0.0 -t 14.0.0 -t 16.0.0 --strip -u $env:GITHUB_TOKEN --include-regex "\.(node|dll)$"}
