ffplay -i output/0.flv -autoexit; sleep 3
ffplay -i output/10.flv -autoexit; sleep 3
ffplay -i output/11.flv -autoexit; sleep 3
ffplay -i output/12.flv -autoexit; sleep 3
ffplay -i output/13.flv -autoexit; sleep 3
ffplay -i output/14.flv -autoexit; sleep 3
ffplay -i output/15.flv -autoexit; sleep 3
ffplay -i output/16.flv -autoexit; sleep 3
ffplay -i output/17.flv -autoexit; sleep 3
ffplay -i output/19.flv -autoexit; sleep 3
ffplay -i output/1.flv -autoexit; sleep 3
ffplay -i output/20.flv -autoexit; sleep 3
ffplay -i output/21.flv -autoexit; sleep 3
ffplay -i output/22.flv -autoexit; sleep 3
ffplay -i output/23.flv -autoexit; sleep 3
ffplay -i output/24.flv -autoexit; sleep 3
ffplay -i output/25.flv -autoexit; sleep 3
ffplay -i output/26.flv -autoexit; sleep 3
ffplay -i output/27.flv -autoexit; sleep 3
ffplay -i output/28.flv -autoexit; sleep 3
ffplay -i output/29.flv -autoexit; sleep 3
ffplay -i output/2.flv -autoexit; sleep 3
ffplay -i output/30.flv -autoexit; sleep 3
ffplay -i output/31.flv -autoexit; sleep 3
ffplay -i output/35.flv -autoexit; sleep 3
ffplay -i output/38.flv -autoexit; sleep 3
ffplay -i output/39.flv -autoexit; sleep 3
ffplay -i output/3.flv -autoexit; sleep 3
ffplay -i output/40.flv -autoexit; sleep 3
ffplay -i output/4.flv -autoexit; sleep 3
ffplay -i output/5.flv -autoexit; sleep 3
ffplay -i output/6.flv -autoexit; sleep 3
ffplay -i output/7.flv -autoexit; sleep 3
ffplay -i output/8.flv -autoexit; sleep 3
