language: cpp

git:
  depth: 1
  
sudo: required
dist: trusty

install:
    - bash ci-scripts/$TRAVIS_OS_NAME/travis-install.sh
script:
    - bash ci-scripts/$TRAVIS_OS_NAME/travis-build.sh

matrix:
    include:
        - os: linux
          compiler: gcc
          cache: ccache
        - os: linux
          compiler: clang
        - os: osx
          osx_image: xcode10.1
