from pyjom.modules.informationProcessing.dummyProcessor import dummyProcessor
from pyjom.modules.informationProcessing.localProcessor import FilesystemProcessor
from pyjom.modules.informationProcessing.onlineProcessor import OnlineProcessor
