ffmpeg -ss 0.400000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_0.jpg
ffmpeg -ss 0.600000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_1.jpg
ffmpeg -ss 0.800000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_2.jpg
ffmpeg -ss 1.000000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_3.jpg
ffmpeg -ss 1.200000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_4.jpg
ffmpeg -ss 1.400000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_5.jpg
ffmpeg -ss 1.600000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_6.jpg
ffmpeg -ss 1.800000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_7.jpg
ffmpeg -ss 2.000000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_8.jpg
ffmpeg -ss 2.200000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_9.jpg
ffmpeg -ss 2.400000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_10.jpg
ffmpeg -ss 2.600000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_11.jpg
ffmpeg -ss 2.800000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_12.jpg
ffmpeg -ss 3.000000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_13.jpg
ffmpeg -ss 3.200000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_14.jpg
ffmpeg -ss 3.400000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_15.jpg
ffmpeg -ss 3.600000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_16.jpg
ffmpeg -ss 3.800000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_17.jpg
ffmpeg -ss 4.000000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_18.jpg
ffmpeg -ss 4.200000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_19.jpg
ffmpeg -ss 4.400000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_20.jpg
ffmpeg -ss 4.600000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_21.jpg
ffmpeg -ss 4.800000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_22.jpg
ffmpeg -ss 5.000000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_23.jpg
ffmpeg -ss 5.200000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_24.jpg
ffmpeg -ss 5.400000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_25.jpg
ffmpeg -ss 5.600000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_26.jpg
ffmpeg -ss 5.800000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_27.jpg
ffmpeg -ss 6.000000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_28.jpg
ffmpeg -ss 6.200000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_29.jpg
ffmpeg -ss 6.400000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_30.jpg
ffmpeg -ss 6.600000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_31.jpg
ffmpeg -ss 6.800000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_32.jpg
ffmpeg -ss 7.000000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_33.jpg
ffmpeg -ss 7.200000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_34.jpg
ffmpeg -ss 7.400000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_35.jpg
ffmpeg -ss 7.600000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_36.jpg
ffmpeg -ss 7.800000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_37.jpg
ffmpeg -ss 8.000000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_38.jpg
ffmpeg -ss 8.200000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_39.jpg
ffmpeg -ss 8.400000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_40.jpg
ffmpeg -ss 8.600000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_41.jpg
ffmpeg -ss 8.800000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_42.jpg
ffmpeg -ss 9.000000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_43.jpg
ffmpeg -ss 9.200000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_44.jpg
ffmpeg -ss 9.400000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_45.jpg
ffmpeg -ss 9.600000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_46.jpg
ffmpeg -ss 9.800000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_47.jpg
ffmpeg -ss 10.000000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_48.jpg
ffmpeg -ss 10.200000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_49.jpg
ffmpeg -ss 10.400000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_50.jpg
ffmpeg -ss 10.600000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_51.jpg
ffmpeg -ss 10.800000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_52.jpg
ffmpeg -ss 11.000000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_53.jpg
ffmpeg -ss 11.200000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_54.jpg
ffmpeg -ss 11.400000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_55.jpg
ffmpeg -ss 11.600000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_56.jpg
ffmpeg -ss 11.800000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_57.jpg
ffmpeg -ss 12.000000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_58.jpg
ffmpeg -ss 12.200000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_59.jpg
ffmpeg -ss 12.400000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_60.jpg
ffmpeg -ss 12.600000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_61.jpg
ffmpeg -ss 12.800000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_62.jpg
ffmpeg -ss 13.000000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_63.jpg
ffmpeg -ss 13.200000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_64.jpg
ffmpeg -ss 13.400000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_65.jpg
ffmpeg -ss 13.600000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_66.jpg
ffmpeg -ss 13.800000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_67.jpg
ffmpeg -ss 14.000000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_68.jpg
ffmpeg -ss 14.200000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_69.jpg
ffmpeg -ss 14.400000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_70.jpg
ffmpeg -ss 14.600000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_71.jpg
ffmpeg -ss 14.800000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_72.jpg
ffmpeg -ss 15.000000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_73.jpg
ffmpeg -ss 15.200000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_74.jpg
ffmpeg -ss 15.400000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_75.jpg
ffmpeg -ss 15.600000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_76.jpg
ffmpeg -ss 15.800000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_77.jpg
ffmpeg -ss 16.000000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_78.jpg
ffmpeg -ss 16.200000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_79.jpg
ffmpeg -ss 16.400000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_80.jpg
ffmpeg -ss 16.600000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_81.jpg
ffmpeg -ss 16.800000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_82.jpg
ffmpeg -ss 17.000000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_83.jpg
ffmpeg -ss 17.200000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_84.jpg
ffmpeg -ss 17.400000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_85.jpg
ffmpeg -ss 17.600000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_86.jpg
ffmpeg -ss 17.800000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_87.jpg
ffmpeg -ss 18.000000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_88.jpg
ffmpeg -ss 18.200000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_89.jpg
ffmpeg -ss 18.400000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_90.jpg
ffmpeg -ss 18.600000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_91.jpg
ffmpeg -ss 18.800000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_92.jpg
ffmpeg -ss 19.000000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_93.jpg
ffmpeg -ss 19.200000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_94.jpg
ffmpeg -ss 19.400000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_95.jpg
ffmpeg -ss 19.600000 -i /root/Desktop/works/pyjom/samples/video/LiEIfnsvn.mp4 -vframes 1 pip_examine/screenshot_96.jpg
